require("dotenv").config();

const CONFIG = {
    ENVIRONMENT: process.env.ENVIRONMENT || "local",
    APP_VERSION: process.env.APP_VERSION || "dev",

    PORT: process.env.PORT || 3000,
    CORS_ORIGIN: process.env.CORS_ORIGIN || "*",
    WEBSOCKET_URL: process.env.WEBSOCKET_URL || "ws://localhost:3000",
    NN_SERVICE_URL: process.env.NN_SERVICE_URL || "http://localhost:8000/api",
    STATE_SAVE_PATH: process.env.STATE_SAVE_PATH || "./data/state.json",
    STATE_SAVE_INTERVAL_MS: 1000 * 60 * 5,

    STATE_UPDATE_INTERVAL_MS: 300,
    STATE_UPDATE_LOOP_RETRY_LIMIT: parseInt(process.env.STATE_UPDATE_LOOP_RETRY_LIMIT || '3', 10),
    GRID_SIZE: 50,
    GRID_TARGET_ENERGY: 15000,

    CREATURE_INITIAL_COUNT: 20,
    CREATURE_INITIAL_ENERGY: 400,
    CREATURE_MAX_ENERGY: 1000,
    CREATURE_ENERGY_LOSS_FACTOR: 1,
    CREATURE_ENERGY_LOSS_BASE: 0.2,
    CREATURE_ENERGY_LOSS_SPEED_FACTOR: 0.4,
    CREATURE_ENERGY_LOSS_TURN_FACTOR: 0.4,
    CREATURE_COLLISION_ENERGY_PENALTY: 7,
    CREATURE_COLLISION_TICKS_TO_FLASH: 4,
    CREATURE_REPRODUCTION_ENERGY_COST: 400,
    CREATURE_VISIBILITY_RADIUS: 15,
    CREATURE_VISIBILITY_FOV_RADIANS: 120 / 180 * Math.PI,
    CREATURE_INTERACTION_RADIUS: 0.9,
    CREATURE_MAX_SPEED: 0.4,
    CREATURE_MAX_TURN_ANGLE_RADIANS: 45 / 180 * Math.PI,
    CREATURE_PATH_MAX_ENTRIES: 5,

    FOOD_MAX_COUNT: 30,    
    FOOD_ENERGY: 130,   
    FOOD_ENERGY_BONUS: 130,
    FOOD_ENERGY_BONUS_MAX_GENERATION: 100,
    
    MUTATION_CHANCE: 0.5,
    TOP_PERFORMERS_COUNT: 5,

    POPULATION_RESTART_THRESHOLD: 3,
    POPULATION_TOP_RATIO: 0.2,
    POPULATION_MUTATED_RATIO: 0.6,
};  

module.exports = CONFIG;
