require("dotenv").config();

const CONFIG = {
    PORT: process.env.PORT || 3000,
    WEBSOCKET_URL: process.env.WEBSOCKET_URL || "ws://localhost:3000",
    AI_SERVER_URL: process.env.AI_SERVER_URL || "http://localhost:8000/api",
    STATE_SAVE_PATH: "./data/state.json",
    STATE_SAVE_INTERVAL: 1000 * 60 * 5,
    STATE_UPDATE_INTERVAL: 500,
    GRID_SIZE: 50,
    TOTAL_ENERGY: 15000,
    CREATURE_INITIAL_COUNT: 20,
    CREATURE_INITIAL_ENERGY: 400,
    CREATURE_MAX_ENERGY: 1000,
    CREATURE_ENERGY_LOSS: 1,
    CREATURE_COLLISION_PENALTY: 5,
    CREATURE_REPRODUCTION_ENERGY_COST: 400,
    CREATURE_VISIBILITY_RADIUS: 10,
    CREATURE_INTERACTION_RADIUS: 0.7,
    CREATURE_MAX_SPEED: 1.0, // one grid cell per update
    CREATURE_MAX_TURN_ANGLE: Math.PI / 3 * 2, // 120 degrees
    CREATURE_PATH_LENGTH: 5,
    MUTATION_CHANCE: 0.5,
    FOOD_MAX_COUNT: 30,    
    FOOD_ENERGY: 150,   
    TOP_PERFORMERS_COUNT: 5,
    RESTART_ON_CREATURE_COUNT: 5
};

module.exports = CONFIG;