name: Determine Environment

on:
  workflow_call:
    outputs:
      environment:
        description: "Deployment environment"
        value: ${{ jobs.setenv.outputs.environment }}

jobs:
  setenv:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setenv.outputs.environment }}
    steps:
      - id: setenv
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}"
          if [[ "$BRANCH" == "qa" ]]; then
            echo "environment=qa" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == "main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi
