name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - qa

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node dependencies
        working-directory: services/web_server
        run: npm install

      - name: Run Jest suites
        working-directory: services/web_server
        run: npm test -- --runInBand

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r services/nn_service/requirements.txt

      - name: Run Pytest suite
        run: PYTHONPATH=services pytest services/nn_service/tests

  e2e:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/qa')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node dependencies
        working-directory: services/web_server
        run: npm install

      - name: Install Playwright browsers
        working-directory: services/web_server
        run: npx playwright install --with-deps chromium

      - name: Run Playwright smoke tests
        working-directory: services/web_server
        run: npm run test:e2e
